[env]
DATABASE_URL = { value = "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}", condition = { env_not_set = ["DATABASE_URL"] } }

[tasks.db_create]
workspace = false
command = "sqlx"
args = ["db", "create", "--database-url", "${DATABASE_URL}"]

[tasks.db_drop]
workspace = false
command = "sqlx"
args = ["db", "drop", "--database-url", "${DATABASE_URL}"]

[tasks.migrate_add]
workspace = false
command = "sqlx"
args = ["migrate", "add", "-r", "${@}"]

[tasks.migrate_run]
workspace = false
command = "sqlx"
args = ["migrate", "run", "--database-url", "${DATABASE_URL}"]

[tasks.migrate_revert]
workspace = false
command = "sqlx"
args = ["migrate", "revert", "--database-url", "${DATABASE_URL}"]

[tasks.watch]
workspace = false
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.db_init]
workspace = false
run_task = [
    { name = ["db_create", "migrate_run", "watch"] },
]
