[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../app-domain" }
adapter = { path = "../app-adapter" }
anyhow = "1.0.71"
derive-new = "0.5.9"
chrono = "0.4.31"
rust_decimal = "1.32.0"
futures = "0.3.29"
