version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    image: linebot-rust-app
    container_name: linebot-rust-app
    working_dir: /app
    command: bash
    tty: true
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    networks:
      - linebot-rust-network

  db:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
      target: 'linebot-rust-db'
    image: linebot-rust-db
    container_name: linebot-rust-db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - linebot-rust-network

  redis:
    image: redis:7.2.1-alpine
    container_name: linebot-rust-redis
    command: redis-server --appendonly yes
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./redis:/data
    networks:
      - linebot-rust-network

networks:
  linebot-rust-network:
    driver: bridge
